plugins:
  - jest

env:
  node: true
  jest: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  linebreak-style: 0
  comma-dangle: off
  no-console: 0
  eol-last: 0
  no-multiple-empty-lines: ['error', { 'max': 1, 'maxEOF': 0 }]
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  object-curly-spacing: ['error', 'always']
  quotes: ['error']
